# Generated by Django 2.1.4 on 2018-12-05 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='best_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='bla', max_length=50),
            preserve_default=False,
        ),
    ]
