# Generated by Django 2.1.4 on 2018-12-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181206_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usuario',
            new_name='user',
        ),
    ]
