# Generated by Django 2.1.4 on 2018-12-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomings', '0002_auto_20181206_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
