# Generated by Django 2.1.4 on 2018-12-06 02:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20181205_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('flag', models.CharField(max_length=25)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('best_day', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)])),
                ('due_day', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
