# Generated by Django 2.1.4 on 2018-12-05 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20181205_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('has_installments', models.BooleanField(default=False)),
                ('installments_number', models.IntegerField(blank=True, null=True)),
                ('installments_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('tags', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
