# Generated by Django 2.1.4 on 2018-12-06 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('shoppings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
