# Generated by Django 2.1.4 on 2018-12-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0002_auto_20181206_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(blank=True, null=True)),
                ('installments_price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='shopping',
            old_name='full_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='has_installments',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='installments_number',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='installments_price',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Card'),
        ),
        migrations.AddField(
            model_name='installment',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppings.Shopping'),
        ),
    ]
