# Generated by Django 2.1.4 on 2018-12-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0003_auto_20181206_0329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number']},
        ),
    ]
