# Generated by Django 2.1.4 on 2018-12-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0004_auto_20181206_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
