# Generated by Django 2.1.4 on 2018-12-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0005_auto_20181206_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
