# Generated by Django 2.1.4 on 2018-12-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='debt_type',
            field=models.IntegerField(choices=[(0, 'Shopping'), (1, 'Loan'), (2, 'HomeExpenses')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('shopping', 'installment_number')},
        ),
    ]
