# Generated by Django 2.1.4 on 2018-12-18 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0010_auto_20181214_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='installments_price',
            new_name='installment_price',
        ),
        migrations.AlterField(
            model_name='shopping',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
